language: python

python:
    - 2.7

virtualenv:
  system_site_packages: true

env:
    # try all python versions with the latest stable numpy and astropy
    - CYTHON_VERSION=0.20.1 NUMPY_VERSION=1.8.0 PANDAS_VERSION=0.12 ASTROPY_VERSION=0.3 SETUP_CMD='test'


before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy python-pandas python-scipy python-h5py python-sphinx python-yaml cython libatlas-dev liblapack-dev gfortran

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   #- pip install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
   - pip install -q --upgrade "Cython==$CYTHON_VERSION$"
   - pip install -q --upgrade "pandas==$PANDAS_VERSION"
   - pip install -q "astropy==$ASTROPY_VERSION"
   - pip install -q coveralls
   - pip install -q pytest
   - pip install -q pytest-cov
   #building inplace
   - python setup.py build_ext --inplace

script:
   - coverage run --source=tardis -m py.test
   # introduce when astropy >= 0.3.1 is out python setup.py test --coverage --skip-docs

after_success:
  coveralls