language: python

python:
    - 2.7

virtualenv:
  system_site_packages: true

env:
    # try all python versions with the latest stable numpy and astropy
    - NUMPY_VERSION=1.7.1 SETUP_CMD='test'


before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy python-pandas python-scipy python-h5py python-sphinx python-yaml cython libatlas-dev liblapack-dev gfortran

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   #- pip install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
   - pip install -q --upgrade Cython --use-mirrors
   - pip install -q --upgrade "pandas==0.12" --use-mirrors


   #- pip install --upgrade scipy --use-mirrors
   - pip install -q astropy --use-mirrors
   - pip install -q coveralls --use-mirrors
   - pip install -q pytest --use-mirrors
   #- pip -q install --upgrade h5py --use-mirrors
   - python setup.py build_ext --inplace

script:
   python setup.py test --coverage

after_success:
  coveralls