name: benchmarks-updated

on:
  push:
    branches:
      - master

  pull_request_target:
    branches:
      - master

    types:
      - opened
      - reopened
      - synchronize
      - labeled # benchmarks label required
  workflow_dispatch:

env: 
  DEPLOY_BRANCH: main

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    if: github.repository_owner == 'tardis-sn' &&
      (github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request_target' &&
      contains(github.event.pull_request.labels.*.name, 'benchmarks')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0

      - name: Checkout pull/${{ github.event.number }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
        if: github.event_name == 'pull_request_target'

      - name: Setup LFS
        uses: ./.github/actions/setup_lfs

      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: benchmark
          init-shell: >-
            bash
          create-args: >-
            python
            asv
            mamba

      - name: Accept all asv questions
        run: asv machine --yes

      - name: Run benchmarks for last 1 commit
        if: github.event_name != 'pull_request_target'
        run: |
          git log -n 1  --pretty=format:"%H" >> tag_commits.txt
          asv run HASHFILE:tag_commits.txt | tee asv-output.log  
          if grep -q failed asv-output.log; then 
            echo "Some benchmarks have failed!"
            exit 1
          fi

      - name: Generate Graphs and HTML
        if: github.event_name != 'pull_request_target'
        run: asv publish
