name: benchmarks

on:
  push:
    branches:
    - master

  pull_request:
    branches:
      - master

    types:
      - opened
      - reopened
      - synchronize
      - labeled  
  workflow_dispatch:
    
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/tardis
        # - os: macos-latest
        #   label: osx-64
        #   prefix: /Users/runner/miniconda3/envs/tardis
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' ||
        github.event_name == 'workflow_dispatch' || 
        contains(github.event.pull_request.labels.*.name, 'run-benchmarks')
    steps:
      - uses: actions/checkout@v2
        with:
          repository: atharva-2001/tardis
          ref: master

      - name: Download Atom Data
        run: |
          REPO_URL="https://dev.azure.com/tardis-sn/TARDIS/_apis/git/repositories/tardis-refdata"
          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=master&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5

      - name: Install asv
        run: pip install asv
      
      - name: Run benchmarks for last 5 commits if not PR
        if: github.event_name != 'pull_request'
        run: |
          git log -n 5  --pretty=format:"%H" >> tag_commits.txt
          asv machine --yes
          asv run HASHFILE:tag_commits.txt | tee asv-output.log  
          if grep -q failed asv-output.log; then 
            echo "Some benchmarks have failed!"
            exit 1
          fi
          
      - name: Generate Graphs and HTML
        if: github.event_name != 'pull_request'
        run: asv publish

      - name: Delete env files
        run: rm -r .asv/env
      
      - name: Push results to results repository
        if: github.event_name != 'pull_request'
        continue-on-error: true
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: .asv
          destination-github-username: atharva-2001
          destination-repository-name: tardis-benchmark-test-results
          user-email: aryaatharva18@gmail.com
          target-branch: main
          target-directory: .asv
      
      - name: Compare HEAD with master if PR
        if: github.event_name == 'pull_request'
        continue-on-error: true # TODO: step failed sporadically while testing
        run: |
          asv continuous --show-stderr ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  | tee asv-output.log  
          if grep -q Traceback asv-output.log; then 
            echo "Some benchmarks have errors!"
            exit 1
          fi
      
      - name: Output logs for comment
        id: asv_logs
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "text<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat asv-output.log)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token:  ${{ secrets.API_TOKEN_GITHUB}}
          issue-number: ${{ github.event.pull_request.number }} 
          body: |
            *\*beep\* \*bop\**
            Hi human, 
            I ran benchmarks as you asked comparing master (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
            Here are the logs produced by ASV.
            Results can also be downloaded as artifacts [**here**](${{ env.URL }}). 
            <details>

              ```
              ${{join(steps.asv_logs.outputs.*, '\n')}}
              ${{ steps.asv_logs.outputs.LOGS }}
              ```
            </details>
        env:
          URL: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}?check_suite_focus=true
      
        
      - name: Save results artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: asv-benchmark-results-${{ runner.os }}
          path: .asv/results
      