name: benchmarks-updated

on:
  push:
    branches:
      - '*'

  pull_request_target:
    branches:
      - '*'
  workflow_dispatch:

env: 
  DEPLOY_BRANCH: main

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0

      # - name: Setup LFS
      #   uses: ./.github/actions/setup_lfs

      # - name: Setup Mamba
      #   uses: mamba-org/setup-micromamba@v1
      #   with:
      #     environment-name: benchmark
      #     init-shell: >-
      #       bash
      #     create-args: >-
      #       python
      #       asv
      #       mamba
      #       conda-libmamba-solver=23.3.0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          auto-activate-base: true
      
      - run: |
          conda install -n base conda=22.11.1 python>=3.10
          conda install -n base conda-libmamba-solver
          conda install asv
          
      - name: Accept all asv questions
        run: asv machine --yes

      - name: Run benchmarks for last 1 commit
        if: github.event_name != 'pull_request_target'
        run: |
          git log -n 1  --pretty=format:"%H" >> tag_commits.txt
          asv run HASHFILE:tag_commits.txt --quick --parallel | tee asv-output.log  
          if grep -q failed asv-output.log; then 
            echo "Some benchmarks have failed!"
            exit 1
          fi

      - name: Generate Graphs and HTML
        if: github.event_name != 'pull_request_target'
        run: asv publish
