name: benchmarks

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash -l {0}

# permissions:
#       pages: write      # to deploy to Pages
#       id-token: write   # to verify the deployment 

jobs:
  build:
    strategy:
      matrix:
        include:

        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/tardis

        # - os: macos-latest
        #   label: osx-64
        #   prefix: /Users/runner/miniconda3/envs/tardis

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: atharva-2001/tardis
          ref: benchmark_base

      - name: Download Atom Data
        run: |
          wget https://raw.githubusercontent.com/tardis-sn/tardis/83cd1f13088e95e087c97370af04bda6cf9956b7/.ci-helpers/download_reference_data.sh
          bash download_reference_data.sh atom_data/kurucz_cd23_chianti_H_He.h5
          mv ./tardis-refdata/atom_data/kurucz_cd23_chianti_H_He.h5  benchmarks/data/
        
      - name: Install asv
        run: pip install asv
      
      - name: Run benchmarks for last 5 commits if not PR
        # if: github.event_name != 'pull_request'
        run: |
          git log -n 5  --pretty=format:"%H" >> tag_commits.txt
          asv machine --yes
          asv run HASHFILE:tag_commits.txt -e
          
      - run: asv publish
      
      - name: Push results to repo
        if: github.event_name != 'pull_request'
        continue-on-error: true
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_PAT_TEMP}}
        with:
          source-directory: .asv
          destination-github-username: atharva-2001
          destination-repository-name: tardis-benchmark-test-results
          user-email: aryaatharva18@gmail.com
          target-branch: gh-pages
      
      - name: Compare HEAD with master if PR
        if: github.event_name == 'pull_request'
        continue-on-error: true # TODO: step failed sporadically while testing
        run: |
          asv continuous --show-stderr ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  | tee asv-output.log  
          if grep -q Traceback asv-output.log; then 
            echo "Some benchmarks have errors!"
          fi
      
      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token:  ${{ secrets.BOT_TOKEN}}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: asv-output.log  
      