name: benchmarks

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash -l {0}

# permissions:
#       pages: write      # to deploy to Pages
#       id-token: write   # to verify the deployment 

jobs:
  build:
    strategy:
      matrix:
        include:

        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/tardis

        # - os: macos-latest
        #   label: osx-64
        #   prefix: /Users/runner/miniconda3/envs/tardis
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: atharva-2001/tardis
          ref: benchmark_simulation
          # fetch-depth: 10

      # - name: Setup environment
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #       miniforge-variant: Mambaforge
      #       miniforge-version: latest
      #       activate-environment: tardis
      #       use-mamba: true

      # - uses: actions/cache@v2
      #   with:
      #     path: ${{ matrix.prefix }}
      #     key: conda-${{ matrix.label }}-${{ hashFiles('conda-${{ matrix.label }}.lock') }}-${{ env.CACHE_NUMBER }}
      #   id: cache-conda

      # - name: Update environment
      #   run: mamba update -n tardis --file conda-${{ matrix.label }}.lock
      #   if: steps.cache-conda.outputs.cache-hit != 'true'

      # - name: Install package
      #   run: pip install -e .
      
      - run: wget https://raw.githubusercontent.com/tardis-sn/tardis/83cd1f13088e95e087c97370af04bda6cf9956b7/.ci-helpers/download_reference_data.sh
        # working-directory: asv/data

      - run: bash download_reference_data.sh atom_data/kurucz_cd23_chianti_H_He.h5

      - run: tree  ./tardis-refdata -L 2   
      
      - run: mv ./tardis-refdata/atom_data/kurucz_cd23_chianti_H_He.h5 asv/data/
      
      - name: Install asv
        run: pip install asv
      
      - run: asv machine --yes

      - name: Run benchmarks for last 10 commits if not PR
        if: github.event_name != 'pull_request'
        run: |
          git log -n 10  --pretty=format:"%H" >> tag_commits.txt
          asv run HASHFILE:tag_commits.txt -e
          asv publish
      
      - name: Push results to repo
        if: github.event_name != 'pull_request'
        continue-on-error: true
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_PAT_TEMP}}
        with:
          source-directory: .asv
          destination-github-username: atharva-2001
          destination-repository-name: tardis-benchmark-test-results
          user-email: aryaatharva18@gmail.com
          target-branch: gh-pages
      
      - name: Compare HEAD with master if PR
        if: github.event_name == 'pull_request'
        run: |
          asv continuous --show-stderr ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA}  | tee asv-output.log  
          if grep -q Traceback asv-output.log; then 
            echo "Some benchmarks have errors!"
          fi
      
      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token:  ${{ secrets.DEPLOY_PAT_TEMP }}
          issue-number: ${{ github.event.pull_request.number }}
          # edit-mode: replace
          body-file: asv-output.log  
      



      