name: benchmarks-updated

on:
  push:
    branches:
      - '*'

  pull_request_target:
    branches:
      - '*'
  workflow_dispatch:

env: 
  DEPLOY_BRANCH: main

defaults:
  run:
    shell: bash -l {0}


jobs:
  bench-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List names of all files we want to move on temporary basis
        id: discover-bench
        run: | 
          output=$(ls *.py | grep -v -E '(benchmark_base|__init__).py' | jq -R . | jq -cs . )  
          echo "file_list=$output" >> "$GITHUB_OUTPUT"
        working-directory: "./benchmarks"
    
    outputs:
      discover-bench: ${{ steps.discover-bench.outputs.file_list }}

  build:
    needs: bench-matrix
    strategy:
      matrix:
        test-path: ${{fromJson(needs.bench-matrix.outputs.discover-bench)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0

      - name: Setup LFS
        uses: ./.github/actions/setup_lfs

      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: benchmark
          init-shell: >-
            bash
          create-args: >-
            python
            asv
            mamba
          
      - name: Accept all asv questions
        run: asv machine --yes

      - name: Run benchmarks for last 1 commit
        if: github.event_name != 'pull_request_target'
        run: |
          git log -n 1  --pretty=format:"%H" >> tag_commits.txt
          asv run HASHFILE:tag_commits.txt --quick | tee asv-output.log  
          if grep -q failed asv-output.log; then 
            echo "Some benchmarks have failed!"
            exit 1
          fi
      - name: Generate Graphs and HTML
        if: github.event_name != 'pull_request_target'
        run: asv publish