name: deploy-docs

# Run this when the main branch changes
on:
  workflow_dispatch:
  push:
    branches:
    - deeksha_loggerjb

defaults:
  run:
    shell: bash -l {0}

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: tardis-sn/tardis-regression-data
        path: tardis-regression-data
        lfs: true
        sparse-checkout: |
          atom_data/kurucz_cd23_chianti_H_He.h5
    
    - run: ls tardis-regression-data

    - name: Setup environment
      uses: ./.github/actions/setup_env
      with:
        os-label: linux-64

    - name: Copy atom_data
      run: |
        mkdir -p ~/Downloads/tardis-data && cp -a ./tardis-regression-data/atom_data/. ~/Downloads/tardis-data
      
    - run: |
        micromamba install jupyter-book sphinx-autoapi ipywidgets jupyter_contrib_nbextensions click jinja2 "jsonschema<5" "linkify-it-py>=2,<3" "myst-nb>=1,<3" "myst-parser>=1,<3" pyyaml "sphinx>=5,<8" sphinx-comments sphinx-copybutton "sphinx-external-toc>=1.0.1,<2" "sphinx-jupyterbook-latex>=1,<2" "sphinx-design>=0.5,<1" "sphinx-thebe>=0.3.1,<1" "sphinx-book-theme>=1.1.0,<2" "sphinxcontrib-bibtex>=2.5.0,<3" "sphinx-multitoc-numbering>=0.1.3,<1" pre-commit pyppeteer altair bokeh folium ipywidgets jupytext matplotlib nbclient pandas plotly sphinx-click sphinx-proof "sphinxext-rediraffe~=0.2.3" sympy beautifulsoup4 cookiecutter coverage pytest "pytest-cov" pytest-regressions pytest-timeout pytest-xdist "pydata-sphinx-theme>=0.15.3" texsoup
        jupyter nbextension enable --py widgetsnbextension
        jupyter contrib nbextension install --user
        jupyter nbextension enable varInspector/main
        pip install sphinx-examples sphinx_inline_tabs sphinx_togglebutton
        pip install -e . --user
      # shell: micromamba-shell {0}

    # Build the book
    - name: Build the book
      # shell: micromamba-shell {0}
      run: |
        jupyter-book build --all docs_new/k1.ipynb
  
    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "docs_new/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
