name: tardis-carsus-compatibility-check

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

env:
  XUVTOP: /tmp/chianti
  CHIANTI_DL_URL: https://download.chiantidatabase.org
  CHIANTI_DB_VER: CHIANTI_v9.0.1_database.tar.gz
  NBCONVERT_CMD: jupyter nbconvert --execute --ExecutePreprocessor.timeout=600 --to html
  CMFGEN_DL_URL: http://kookaburra.phyast.pitt.edu/hillier/cmfgen_files
  CMFGEN_DB_VER: atomic_data_15nov16.tar.gz
  # original reference data
  REF1_PATH: /home/runner/work/tardis/tardis-refdata/unit_test_data_org.h5
  # generated reference data using the new atomic file 
  REF2_PATH: /home/runner/work/tardis/tardis-refdata/unit_test_data.h5
  PYTEST_FLAGS: --tardis-refdata=${{ github.workspace }}/tardis-refdata 
                --generate-reference


defaults:
      run:
        shell: bash -l {0}


jobs:
  carsus-build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0

      - name: Clone tardis-sn/carsus
        uses: actions/checkout@v2
        with:
          repository: tardis-sn/carsus
          path: carsus/
        
      - uses: actions/cache@v2
        with:
          path: ${{ env.XUVTOP }}
          key: ${{ runner.os }}-${{ env.CHIANTI_DB_VER }}
        id: chianti-cache

      - name: Download Chianti database
        run: |
            mkdir -p ${{ env.XUVTOP }}
            wget -q ${{ env.CHIANTI_DL_URL }}/${{ env.CHIANTI_DB_VER }} -O ${{ env.XUVTOP }}/chianti.tar.gz
            tar -zxf ${{ env.XUVTOP }}/chianti.tar.gz -C ${{ env.XUVTOP }}
        if: steps.chianti-cache.outputs.cache-hit != 'true'
      
      - uses: actions/cache@v2
        with:
          path: /tmp/atomic
          key: ${{ env.CMFGEN_DB_VER }}
        id: cmfgen-cache

      - name: Download CMFGEN database
        run: |
            wget -q -U "Mozilla/4.0" ${{ env.CMFGEN_DL_URL }}/${{ env.CMFGEN_DB_VER }} -O /tmp/atomic.tar.gz
            tar -zxf /tmp/atomic.tar.gz -C /tmp
        if: steps.cmfgen-cache.outputs.cache-hit != 'true'

      - name: Setup carsus environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            environment-file: carsus/carsus_env3.yml
            activate-environment: carsus
            use-mamba: true

      - name: Install package
        run: pip install -e carsus/

      - name: Run notebooks
        run: |
          ${{ env.NBCONVERT_CMD }} carsus/docs/quickstart.ipynb
        env:
          CARSUS_REFDATA: ${{ github.workspace }}/carsus-refdata
        
      - name: upload atom data
        uses: actions/upload-artifact@v2
        with:
          name: atom-data
          path: carsus/docs/kurucz_cd23_chianti_He_cmfgen_H_Si_I-II.h5
  
  tardis-build:
    needs: carsus-build
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/tardis

    #     - os: macos-latest
    #       label: osx-64
    #       prefix: /Users/runner/miniconda3/envs/tardis
          
    # name: ${{ matrix.label }}
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: tardis-sn/tardis
          
      - uses: actions/checkout@v2
        with:
          repository: atharva-2001/tardis-refdata
          ref: refdata_compare
          path: tardis-refdata
          lfs: true
        
      - name: Fetch lfs objects
        run: |
             cd tardis-refdata
             git lfs checkout 

      - name: Setup TARDIS environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: tardis
            use-mamba: true

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: conda-${{ matrix.label }}-${{ hashFiles('conda-${{ matrix.label }}.lock') }}-${{ env.CACHE_NUMBER }}
        id: cache-conda

      - name: Update environment
        run: mamba update -n tardis --file conda-${{ matrix.label }}.lock
        if: steps.cache-conda.outputs.cache-hit != 'true'

      - name: Install package
        run: pip install -e .
        
      # only run this steop when carsus build is done
      - name: Download atom data
        uses: actions/download-artifact@v2
        with:
          name: atom-data
          path: carsus/docs/kurucz_cd23_chianti_He_cmfgen_H_Si_I-II.h5
          # path: kurucz_cd23_chianti_He_cmfgen_H_Si_I-II.h5
      
      - name: Replace atomic data in reference data repository with the generated atomic data
        run: cp tardis/kurucz_cd23_chianti_He_cmfgen_H_Si_I-II.h5 tardis-refdata/atom_data/kurucz_cd23_chianti_H_He.h5
      
      - name: Create copy of reference data for comparision
        run: cp tardis-refdata/unit_test_data.h5 tardis-refdata/unit_test_data_org.h5 
      
      - name: Upload reference data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: reference data
          path: tardis-refdata/unit_test_data_org.h5
  
      - name: Print directory tree
        run: tree

      - name: Run tests and generate new reference data
        run:  pytest tardis ${{ env.PYTEST_FLAGS }}

      - name: Run notebook to test spectrum
        run: |
            ${{ env.NBCONVERT_CMD }} --allow-errors "tardis-refdata/notebooks/ref_data_compare copy.ipynb"
      
      - name: Upload spectrum notebook
        uses: actions/upload-artifact@v2
        with:
          path: tardis/tests/test_spectrum.html
        
      



