name: main

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  matrix:
    if: github.repository_owner == 'tardis-sn'
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix:
        label: [osx-arm64, linux-64]
        include:
          - label: osx-arm64
            os: macos-latest
            prefix: /Users/runner/miniconda3/envs/tardis

          - label: linux-64
            os: ubuntu-latest
            prefix: /usr/share/miniconda3/envs/tardis

    uses: ./.github/workflows/new_tests.yml # calls the one above ^
    with:
      run_label: ${{ matrix.label }}
    secrets: inherit