name: relativity-bug

on:
  push:
  pull_request:

jobs:
  test-cache:
    uses: ./.github/workflows/lfs-cache.yml
    with:
      atom-data-sparse: true
      regression-data-repo: tardis-sn/tardis-regression-data
      allow_lfs_pull: false

  test-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout TARDIS repository
        uses: actions/checkout@v4
        with:
          ref: f7a3ce9b7ffbd64536ae66eee577be436607eb25
          
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-linux-64.lock
          environment-name: tardis-bisect
          cache-environment: true

      - name: Install qgridnext
        run: pip install qgridnext
          
      - name: Setup LFS
        uses: ./.github/actions/setup_lfs
        with:
          atom-data-sparse: true
          
      - name: Install TARDIS in development mode
        shell: micromamba-shell {0}
        run: |
          pip install -e .
          
      - name: Download test notebook
        run: |
          wget https://raw.githubusercontent.com/atharva-2001/lfs-investigation/main/running_tardis_relativity_.ipynb
          
      - name: Execute notebook
        shell: micromamba-shell {0}
        run: |
          jupyter nbconvert --to notebook --execute running_tardis_relativity_.ipynb \
            --output executed_running_tardis_relativity_.ipynb \
            --output-dir ./notebook_outputs
            
      - name: Save executed notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook-f7a3ce9b7ffbd64536ae66eee577be436607eb25
          path: |
            ./notebook_outputs/
            ./*.dat
            ./outputs/
          retention-days: 30
          if-no-files-found: warn
          
      - name: Save commit information
        run: |
          echo "Commit: f7a3ce9b7ffbd64536ae66eee577be436607eb25" > commit_info.txt
          echo "Date: $(date)" >> commit_info.txt
          git log -1 --oneline >> commit_info.txt
          
      - name: Upload commit info
        uses: actions/upload-artifact@v4
        with:
          name: commit-info-f7a3ce9b7ffbd64536ae66eee577be436607eb25
          path: commit_info.txt
          retention-days: 30
