name: relativity-bug

on:
  push:
  pull_request:

jobs:
  test-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout TARDIS repository
        uses: actions/checkout@v4
        with:
          ref: f7a3ce9b7ffbd64536ae66eee577be436607eb25

      - name: Clone tardis-sn/tardis-regression-data
        uses: actions/checkout@v4
        with:
          repository: tardis-sn/tardis-regression-data
          path: tardis-regression-data
          sparse-checkout: atom_data/kurucz_cd23_chianti_H_He.h5
          lfs: false

      - name: Restore LFS cache
        uses: actions/cache/restore@v4
        id: lfs-cache-regression-data
        with:
          path: tardis-regression-data/.git/lfs
          key: atom-data

      - name: Git LFS Pull Atom Data
        if: steps.lfs-cache-regression-data.outputs.cache-hit != 'true'
        run: git lfs pull --include=atom_data/kurucz_cd23_chianti_H_He_latest.h5
        working-directory: tardis-regression-data
      
      - name: Save LFS cache if not found
        uses: actions/cache/save@v4
        if: steps.lfs-cache-regression-data.outputs.cache-hit != 'true'
        with:
          path: tardis-regression-data/.git/lfs
          key: atom-data

      - name: Git LFS Checkout (Sparse)
        run: git lfs checkout atom_data/kurucz_cd23_chianti_H_He.h5
        working-directory: tardis-regression-data
    
      - name: Copy atom data to Downloads
        run: |
          cp --parents  ${{ github.workspace }}/tardis-regression-data/atom_data/kurucz_cd23_chianti_H_He.h5 /home/runner/Downloads/tardis-data/atom_data
          
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-linux-64.lock
          environment-name: tardis-bisect
          cache-environment: true

      - name: Install qgridnext
        run: pip install qgridnext
          
      - name: Install TARDIS in development mode
        shell: micromamba-shell {0}
        run: |
          pip install -e .


      - name: Download test notebook
        run: |
          wget https://raw.githubusercontent.com/atharva-2001/lfs-investigation/main/running_tardis_relativity_.ipynb
          
      - name: Execute notebook
        shell: micromamba-shell {0}
        run: |
          jupyter nbconvert --to notebook --execute running_tardis_relativity_.ipynb \
            --output executed_running_tardis_relativity_.ipynb \
            --output-dir ./notebook_outputs
            
      - name: Save executed notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook-f7a3ce9b7ffbd64536ae66eee577be436607eb25
          path: |
            ./notebook_outputs/
            ./*.dat
            ./outputs/
          retention-days: 30
          if-no-files-found: warn
          
      - name: Save commit information
        run: |
          echo "Commit: f7a3ce9b7ffbd64536ae66eee577be436607eb25" > commit_info.txt
          echo "Date: $(date)" >> commit_info.txt
          git log -1 --oneline >> commit_info.txt
          
      - name: Upload commit info
        uses: actions/upload-artifact@v4
        with:
          name: commit-info-f7a3ce9b7ffbd64536ae66eee577be436607eb25
          path: commit_info.txt
          retention-days: 30
