#  For more information about TARDIS pipelines, please refer to:
#
#    https://tardis-sn.github.io/tardis/development/continuous_integration.html

name: tests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
    
    types:
      - opened
      - reopened
      - synchronize
      - labeled

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  PYTEST_FLAGS: --tardis-refdata=${{ github.workspace }}/tardis-refdata --tardis-regression-data=${{ github.workspace }}/tardis-regression-data
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

defaults:
  run:
    shell: bash -l {0}
 
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
    

jobs:
  codecov:
    if: github.repository_owner == 'tardis-sn'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup LFS
        uses: ./.github/actions/setup_lfs
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          os-label: linux-64
      - name: Generate coverage report
        run: |
          pytest --cov=tardis --cov-report=xml --cov-report=html
      - uses: codecov/codecov-action@v4
        if: always()
        with:
          fail_ci_if_error: true
          token: ${{ env.CODECOV_TOKEN }}
          verbose: true

  tests:
    name: ${{ matrix.continuum }} continuum ${{ matrix.os }}
    if: github.repository_owner == 'tardis-sn'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        label: [osx-arm64, linux-64]
        continuum: ['not', '']
        include:
          - label: osx-arm64
            os: macos-latest
            prefix: /Users/runner/miniconda3/envs/tardis

          - label: linux-64
            os: ubuntu-latest
            prefix: /usr/share/miniconda3/envs/tardis
    steps:
      - uses: actions/checkout@v4

      - name: Setup LFS
        uses: ./.github/actions/setup_lfs
      
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          os-label: ${{ matrix.label }}
      
      - name: Install package editable
        run: |
          pip install -e . --user

      - name: Run tests
        run: pytest tardis ${{ env.PYTEST_FLAGS }} -m "${{ matrix.continuum }} continuum"
      
#       - name: Set install path
#         if: matrix.pip == false
#         run: |
#           directory_path="."
#           echo "TARDIS_PIP_PATH=$directory_path" >> $GITHUB_ENV

      - name: Run tests
        run: pytest tardis ${{ env.PYTEST_FLAGS }} -m "not (continuum or rpacket_tracking)"
        working-directory: ${{ env.TARDIS_PIP_PATH }}
        if: always()
      
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)

#       - name: Run continuum tests
#         run: pytest tardis ${{ env.PYTEST_FLAGS }} -m continuum
#         working-directory: ${{ env.TARDIS_PIP_PATH }}
#         if: always()

      - name: Run rpacket tracking tests
        run: pytest tardis ${{ env.PYTEST_FLAGS }} -m rpacket_tracking
        working-directory: ${{ env.TARDIS_PIP_PATH }}
        if: always()
      
#       - name: Refdata Generation tests
#         run: pytest tardis ${{ env.PYTEST_FLAGS }} --generate-reference
#         working-directory: ${{ env.TARDIS_PIP_PATH }}
#         if: contains(github.event.pull_request.labels.*.name, 'run-generation-tests') || github.ref == 'refs/heads/master'
