#  For more information about TARDIS pipelines, please refer to:
#
#    https://tardis-sn.github.io/tardis/development/continuous_integration.html

name: tests

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # run at midnight every Sunday


env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  PYTEST_FLAGS: --tardis-refdata=${{ github.workspace }}/tardis-refdata
                --cov=tardis --cov-report=xml --cov-report=html
  PYTEST_FLAGS_COMPARE: --tardis-refdata=${{ github.workspace }}/tardis-refdata-gen --generate-reference
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  # original reference data
  REF1_PATH: ${{ github.workspace }}/tardis-refdata/unit_test_data.h5
  # generated reference data using the latest commit
  REF2_PATH: ${{ github.workspace }}/tardis-refdata-gen/unit_test_data.h5

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    if: github.repository_owner == 'tardis-sn'
    strategy:
      matrix:
        include:

        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/tardis

        - os: macos-latest
          label: osx-64
          prefix: /Users/runner/miniconda3/envs/tardis

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    outputs:
      step-ref-check-trig: ${{ steps.ref-equal-check.outcome }} # success or failure of refdata comparison
    steps:
      - uses: actions/checkout@v2

      - name: Clone tardis-sn/tardis-refdata
        uses: actions/checkout@v2
        with:
          repository: tardis-sn/tardis-refdata
          path: tardis-refdata
          lfs: false

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        working-directory: tardis-refdata

      - name: Restore LFS cache
        uses: actions/cache/restore@v3
        id: lfs-cache
        with:
          path: tardis-refdata/.git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('tardis-refdata/.lfs-assets-id') }}-v1

      - name: Git LFS Pull
        run: git lfs pull
        working-directory: tardis-refdata
        if: steps.lfs-cache.outputs.cache-hit != 'true'
      
      - name: Git LFS Checkout
        run: git lfs checkout
        working-directory: tardis-refdata
        if: steps.lfs-cache.outputs.cache-hit == 'true'
      
      - name: Save LFS cache if not found
        # uses fake ternary 
        # for reference: https://github.com/orgs/community/discussions/26738#discussioncomment-3253176
        if: ${{ steps.lfs-cache.outputs.cache-hit != 'true'  && always() || false }}
        uses: actions/cache/save@v3
        id: lfs-cache-save
        with:
          path: tardis-refdata/.git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('tardis-refdata/.lfs-assets-id') }}-v1

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: tardis
            use-mamba: true

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: conda-${{ matrix.label }}-${{ hashFiles('conda-${{ matrix.label }}.lock') }}-${{ env.CACHE_NUMBER }}
        id: cache-conda

      - name: Update environment
        run: mamba update -n tardis --file conda-${{ matrix.label }}.lock
        if: steps.cache-conda.outputs.cache-hit != 'true'

      - name: Install package
        run: pip install -e .

      - name: Run tests
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: pytest tardis ${{ env.PYTEST_FLAGS }}
      
      - name: Download refdata_compare notebook
        if: ${{ !(github.event_name == 'push' || github.event_name == 'schedule') }}
        run: wget https://raw.githubusercontent.com/tardis-sn/tardis-refdata/master/notebooks/ref_data_compare_from_paths.ipynb
      
      - name: Generate reference data for comparison
        if: ${{ !(github.event_name == 'push' || github.event_name == 'schedule') }}
        run: pytest tardis ${{ env.PYTEST_FLAGS_COMPARE }}
      
      - name: Compare Reference Data
        if: ${{ !(github.event_name == 'push' || github.event_name == 'schedule') }}
        run: |
            jupyter nbconvert ${{ env.NBCONVERT_FLAGS }} ref_data_compare_from_paths.ipynb
      
      - name: Upload comparison notebook
        if: ${{ !(github.event_name == 'push' || github.event_name == 'schedule') }}
        uses: actions/upload-artifact@v2
        with:
          name: Comparison Notebook
          path: ref_data_compare_from_paths.html
      
      - name: Check if reference data are equal
        if: ${{ !(github.event_name == 'push' || github.event_name == 'schedule') }}
        id: ref-equal-check
        # continue-on-error: true
        run: if [ "$(cat ../refdata_compare_result)" == "REFDATA COMPARISON FAILED" ]; then exit 1; fi

      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      
  refdata-check:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.ref-check-trig == 'failure' && github.repository_owner == 'tardis-sn'
    steps:
      - run: exit 1
